-- CreateEnum
CREATE TYPE "OnboardingStage" AS ENUM ('APPLICATION', 'DOCUMENT_SUBMISSION', 'EVALUATION', 'CONTRACT_NEGOTIATION', 'CONTRACT_SIGNING', 'SYSTEM_SETUP', 'TRAINING', 'GO_LIVE', 'COMPLETED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "DocumentType" ADD VALUE 'LICENSE';
ALTER TYPE "DocumentType" ADD VALUE 'REGISTRATION';
ALTER TYPE "DocumentType" ADD VALUE 'FACILITY_PHOTOS';
ALTER TYPE "DocumentType" ADD VALUE 'OWNERSHIP_PROOF';
ALTER TYPE "DocumentType" ADD VALUE 'STAFF_CREDENTIALS';

-- CreateTable
CREATE TABLE "OnboardingApplication" (
    "id" TEXT NOT NULL,
    "applicationNumber" TEXT NOT NULL,
    "hospitalName" TEXT NOT NULL,
    "legalName" TEXT NOT NULL,
    "registrationNumber" TEXT NOT NULL,
    "taxId" TEXT,
    "establishedDate" TIMESTAMP(3),
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "alternatePhone" TEXT,
    "website" TEXT,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "lga" TEXT NOT NULL,
    "postalCode" TEXT,
    "ownerName" TEXT NOT NULL,
    "ownerEmail" TEXT NOT NULL,
    "ownerPhone" TEXT NOT NULL,
    "ownerNin" TEXT,
    "facilityType" TEXT NOT NULL,
    "bedCapacity" INTEGER,
    "staffCount" INTEGER,
    "servicesOffered" TEXT[],
    "specializations" TEXT[],
    "hasEmergency" BOOLEAN NOT NULL DEFAULT false,
    "hasPharmacy" BOOLEAN NOT NULL DEFAULT false,
    "hasLaboratory" BOOLEAN NOT NULL DEFAULT false,
    "hasRadiology" BOOLEAN NOT NULL DEFAULT false,
    "status" "ApplicationStatus" NOT NULL DEFAULT 'SUBMITTED',
    "submittedAt" TIMESTAMP(3),
    "submittedBy" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "reviewedBy" TEXT,
    "approvedAt" TIMESTAMP(3),
    "approvedBy" TEXT,
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnboardingApplication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OnboardingDocument" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "documentType" "DocumentType" NOT NULL,
    "documentName" TEXT NOT NULL,
    "originalFileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "checksum" TEXT,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "verifiedAt" TIMESTAMP(3),
    "verifiedBy" TEXT,
    "verificationNotes" TEXT,
    "expiryDate" TIMESTAMP(3),
    "uploadedBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnboardingDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EvaluationScore" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "evaluatorId" TEXT NOT NULL,
    "facilityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "facilityNotes" TEXT,
    "staffingScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "staffingNotes" TEXT,
    "equipmentScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "equipmentNotes" TEXT,
    "complianceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "complianceNotes" TEXT,
    "financialScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "financialNotes" TEXT,
    "locationScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "locationNotes" TEXT,
    "servicesScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "servicesNotes" TEXT,
    "reputationScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "reputationNotes" TEXT,
    "totalScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "recommendation" TEXT NOT NULL,
    "generalNotes" TEXT,
    "riskAssessment" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "evaluatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EvaluationScore_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OnboardingContract" (
    "id" TEXT NOT NULL,
    "contractNumber" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "hospitalId" TEXT,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'PARTNERSHIP',
    "templateId" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "autoRenew" BOOLEAN NOT NULL DEFAULT false,
    "renewalPeriodMonths" INTEGER,
    "revenueSharePercentage" DOUBLE PRECISION,
    "monthlyFee" DOUBLE PRECISION,
    "setupFee" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'NGN',
    "paymentTerms" TEXT,
    "content" TEXT NOT NULL,
    "termsAndConditions" TEXT,
    "specialClauses" TEXT[],
    "status" "ContractStatus" NOT NULL DEFAULT 'DRAFT',
    "sentAt" TIMESTAMP(3),
    "viewedAt" TIMESTAMP(3),
    "hospitalSignedAt" TIMESTAMP(3),
    "hospitalSignedBy" TEXT,
    "hospitalSignatureData" TEXT,
    "ghmsoSignedAt" TIMESTAMP(3),
    "ghmsoSignedBy" TEXT,
    "ghmsoSignatureData" TEXT,
    "documentUrl" TEXT,
    "signedDocumentUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnboardingContract_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContractTemplate" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "content" TEXT NOT NULL,
    "variables" JSONB,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ContractTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OnboardingProgress" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "hospitalId" TEXT,
    "currentStage" "OnboardingStage" NOT NULL DEFAULT 'APPLICATION',
    "overallProgress" INTEGER NOT NULL DEFAULT 0,
    "applicationCompleted" BOOLEAN NOT NULL DEFAULT false,
    "applicationCompletedAt" TIMESTAMP(3),
    "documentsCompleted" BOOLEAN NOT NULL DEFAULT false,
    "documentsCompletedAt" TIMESTAMP(3),
    "evaluationCompleted" BOOLEAN NOT NULL DEFAULT false,
    "evaluationCompletedAt" TIMESTAMP(3),
    "contractCompleted" BOOLEAN NOT NULL DEFAULT false,
    "contractCompletedAt" TIMESTAMP(3),
    "signingCompleted" BOOLEAN NOT NULL DEFAULT false,
    "signingCompletedAt" TIMESTAMP(3),
    "systemSetupCompleted" BOOLEAN NOT NULL DEFAULT false,
    "systemSetupCompletedAt" TIMESTAMP(3),
    "trainingCompleted" BOOLEAN NOT NULL DEFAULT false,
    "trainingCompletedAt" TIMESTAMP(3),
    "goLiveCompleted" BOOLEAN NOT NULL DEFAULT false,
    "goLiveCompletedAt" TIMESTAMP(3),
    "isCompleted" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" TIMESTAMP(3),
    "assignedTo" TEXT,
    "notes" TEXT,
    "blockers" TEXT[],
    "nextActions" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnboardingProgress_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OnboardingChecklist" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "item" TEXT NOT NULL,
    "description" TEXT,
    "isRequired" BOOLEAN NOT NULL DEFAULT true,
    "isCompleted" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" TIMESTAMP(3),
    "completedBy" TEXT,
    "notes" TEXT,
    "orderIndex" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnboardingChecklist_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EvaluationCriteria" (
    "id" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "criterion" TEXT NOT NULL,
    "description" TEXT,
    "weight" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "maxScore" DOUBLE PRECISION NOT NULL DEFAULT 100,
    "passThreshold" DOUBLE PRECISION NOT NULL DEFAULT 60,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EvaluationCriteria_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "OnboardingApplication_applicationNumber_key" ON "OnboardingApplication"("applicationNumber");

-- CreateIndex
CREATE UNIQUE INDEX "OnboardingApplication_registrationNumber_key" ON "OnboardingApplication"("registrationNumber");

-- CreateIndex
CREATE UNIQUE INDEX "OnboardingApplication_email_key" ON "OnboardingApplication"("email");

-- CreateIndex
CREATE INDEX "OnboardingApplication_applicationNumber_idx" ON "OnboardingApplication"("applicationNumber");

-- CreateIndex
CREATE INDEX "OnboardingApplication_status_idx" ON "OnboardingApplication"("status");

-- CreateIndex
CREATE INDEX "OnboardingApplication_email_idx" ON "OnboardingApplication"("email");

-- CreateIndex
CREATE INDEX "OnboardingApplication_registrationNumber_idx" ON "OnboardingApplication"("registrationNumber");

-- CreateIndex
CREATE INDEX "OnboardingApplication_state_idx" ON "OnboardingApplication"("state");

-- CreateIndex
CREATE INDEX "OnboardingDocument_applicationId_idx" ON "OnboardingDocument"("applicationId");

-- CreateIndex
CREATE INDEX "OnboardingDocument_documentType_idx" ON "OnboardingDocument"("documentType");

-- CreateIndex
CREATE INDEX "EvaluationScore_applicationId_idx" ON "EvaluationScore"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "EvaluationScore_applicationId_evaluatorId_key" ON "EvaluationScore"("applicationId", "evaluatorId");

-- CreateIndex
CREATE UNIQUE INDEX "OnboardingContract_contractNumber_key" ON "OnboardingContract"("contractNumber");

-- CreateIndex
CREATE UNIQUE INDEX "OnboardingContract_applicationId_key" ON "OnboardingContract"("applicationId");

-- CreateIndex
CREATE INDEX "OnboardingContract_contractNumber_idx" ON "OnboardingContract"("contractNumber");

-- CreateIndex
CREATE INDEX "OnboardingContract_status_idx" ON "OnboardingContract"("status");

-- CreateIndex
CREATE INDEX "OnboardingContract_hospitalId_idx" ON "OnboardingContract"("hospitalId");

-- CreateIndex
CREATE INDEX "ContractTemplate_type_isActive_idx" ON "ContractTemplate"("type", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "OnboardingProgress_applicationId_key" ON "OnboardingProgress"("applicationId");

-- CreateIndex
CREATE INDEX "OnboardingProgress_currentStage_idx" ON "OnboardingProgress"("currentStage");

-- CreateIndex
CREATE INDEX "OnboardingProgress_hospitalId_idx" ON "OnboardingProgress"("hospitalId");

-- CreateIndex
CREATE INDEX "OnboardingChecklist_applicationId_idx" ON "OnboardingChecklist"("applicationId");

-- CreateIndex
CREATE INDEX "OnboardingChecklist_category_idx" ON "OnboardingChecklist"("category");

-- CreateIndex
CREATE INDEX "EvaluationCriteria_category_isActive_idx" ON "EvaluationCriteria"("category", "isActive");

-- AddForeignKey
ALTER TABLE "OnboardingDocument" ADD CONSTRAINT "OnboardingDocument_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "OnboardingApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingDocument" ADD CONSTRAINT "OnboardingDocument_uploadedBy_fkey" FOREIGN KEY ("uploadedBy") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EvaluationScore" ADD CONSTRAINT "EvaluationScore_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "OnboardingApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EvaluationScore" ADD CONSTRAINT "EvaluationScore_evaluatorId_fkey" FOREIGN KEY ("evaluatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingContract" ADD CONSTRAINT "OnboardingContract_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "OnboardingApplication"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingContract" ADD CONSTRAINT "OnboardingContract_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingContract" ADD CONSTRAINT "OnboardingContract_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "ContractTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContractTemplate" ADD CONSTRAINT "ContractTemplate_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingProgress" ADD CONSTRAINT "OnboardingProgress_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "OnboardingApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingProgress" ADD CONSTRAINT "OnboardingProgress_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OnboardingChecklist" ADD CONSTRAINT "OnboardingChecklist_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "OnboardingApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
